<?php

namespace ContainerCWCQFFf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VzIFmbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vzI_fmb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vzI_fmb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ECommerceController::index' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::index()', 'getECommerceControllerindexService', true],
            'App\\Controller\\ECommerceController::paginated' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::paginated()', 'getECommerceControllerpaginatedService', true],
            'App\\Controller\\ECommerceController::delete' => ['privates', '.service_locator.OcpBagw.App\\Controller\\ECommerceController::delete()', 'getECommerceControllerdeleteService', true],
            'App\\Controller\\ECommerceController::addCarte' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::addCarte()', 'getECommerceControlleraddCarteService', true],
            'App\\Controller\\ECommerceController::orderAsc' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::orderAsc()', 'getECommerceControllerorderAscService', true],
            'App\\Controller\\ECommerceController::orderDesc' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::orderDesc()', 'getECommerceControllerorderDescService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ECommerceController:index' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::index()', 'getECommerceControllerindexService', true],
            'App\\Controller\\ECommerceController:paginated' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::paginated()', 'getECommerceControllerpaginatedService', true],
            'App\\Controller\\ECommerceController:delete' => ['privates', '.service_locator.OcpBagw.App\\Controller\\ECommerceController::delete()', 'getECommerceControllerdeleteService', true],
            'App\\Controller\\ECommerceController:addCarte' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::addCarte()', 'getECommerceControlleraddCarteService', true],
            'App\\Controller\\ECommerceController:orderAsc' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::orderAsc()', 'getECommerceControllerorderAscService', true],
            'App\\Controller\\ECommerceController:orderDesc' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ECommerceController::orderDesc()', 'getECommerceControllerorderDescService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ECommerceController::index' => '?',
            'App\\Controller\\ECommerceController::paginated' => '?',
            'App\\Controller\\ECommerceController::delete' => '?',
            'App\\Controller\\ECommerceController::addCarte' => '?',
            'App\\Controller\\ECommerceController::orderAsc' => '?',
            'App\\Controller\\ECommerceController::orderDesc' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ECommerceController:index' => '?',
            'App\\Controller\\ECommerceController:paginated' => '?',
            'App\\Controller\\ECommerceController:delete' => '?',
            'App\\Controller\\ECommerceController:addCarte' => '?',
            'App\\Controller\\ECommerceController:orderAsc' => '?',
            'App\\Controller\\ECommerceController:orderDesc' => '?',
        ]);
    }
}
