<?php

namespace ContainerCWCQFFf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getECommerceControllerorderAscService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E7ajBy2.App\Controller\ECommerceController::orderAsc()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E7ajBy2.App\\Controller\\ECommerceController::orderAsc()'] = ($container->privates['.service_locator.E7ajBy2'] ?? $container->load('get_ServiceLocator_E7ajBy2Service'))->withContext('App\\Controller\\ECommerceController::orderAsc()', $container);
    }
}
