<?php

namespace ContainerJcrDC0D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getECommerceControlleraddCarteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OcpBagw.App\Controller\ECommerceController::addCarte()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OcpBagw.App\\Controller\\ECommerceController::addCarte()'] = ($container->privates['.service_locator.OcpBagw'] ?? $container->load('get_ServiceLocator_OcpBagwService'))->withContext('App\\Controller\\ECommerceController::addCarte()', $container);
    }
}
